#!/usr/bin/env python3
"""
prompt-install — Pipe prompt-enhancer output into any AI coding agent's config.

Usage:
    python3 prompt-install.py "a senior Rust dev who prefers functional style" --agent claude
    python3 prompt-install.py "a terse code reviewer" --agent codex --project ~/repos/myapp
    python3 prompt-install.py --file rough-idea.md --agent cursor

Supported agents:
    claude    → CLAUDE.md (project root, auto-loaded every session)
    codex     → .github/copilot-instructions.md
    opencode  → AGENTS.md (auto-discovered)
    cursor    → .cursorrules
    auggie    → AGENTS.md
    aider     → /tmp/persona.md + prints aider launch command
    copilot   → .github/copilot-instructions.md
    all       → writes to all compatible files
"""

import os
import json
import sys
import subprocess
import argparse
from pathlib import Path

ENHANCER = os.path.expanduser("~/repos/tools/prompt-enhancer/prompt-enhancer.py")
PYTHON = "/Users/hongphuc/.pyenv/versions/3.11.6/bin/python3"

AGENT_CONFIGS = {
    "claude": {
        "path": "CLAUDE.md",
        "description": "Claude Code — auto-loaded every session from project root",
        "comment": "# CLAUDE.md — generated by prompt-enhancer\n",
    },
    "codex": {
        "path": ".github/copilot-instructions.md",
        "description": "Codex (OpenAI) — auto-loaded via COPILOT_INSTRUCTIONS",
        "comment": "<!-- Generated by prompt-enhancer -->\n",
    },
    "opencode": {
        "path": "AGENTS.md",
        "description": "OpenCode — auto-discovered from project root",
        "comment": "<!-- Generated by prompt-enhancer -->\n",
    },
    "cursor": {
        "path": ".cursorrules",
        "description": "Cursor — custom AI rules for the project",
        "comment": "// Generated by prompt-enhancer\n",
    },
    "auggie": {
        "path": "AGENTS.md",
        "description": "Auggie (Augment) — auto-discovered from project root",
        "comment": "<!-- Generated by prompt-enhancer -->\n",
    },
    "copilot": {
        "path": ".github/copilot-instructions.md",
        "description": "GitHub Copilot — custom instructions",
        "comment": "<!-- Generated by prompt-enhancer -->\n",
    },
    "aider": {
        "path": None,  # special: prints launch command
        "description": "Aider — pipe via --system-prompt flag",
        "comment": None,
    },
}


def enhance(seed: str, is_file: bool = False) -> str:
    """Run the enhancer and return the generated system prompt."""
    cmd = [PYTHON, ENHANCER, "--no-auto-context"]
    if is_file:
        cmd.extend(["--file", seed])
    else:
        cmd.append(seed)
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=120,
                           env={**os.environ, "PYTHONUNBUFFERED": "1"})
    if result.returncode != 0:
        print(f"Enhancer failed: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout.strip()


def install(prompt_text: str, agent: str, project_dir: str, dry_run: bool = False):
    """Write the enhanced prompt to the agent's config file."""
    config = AGENT_CONFIGS.get(agent)
    if not config:
        print(f"Unknown agent: {agent}. Supported: {', '.join(AGENT_CONFIGS.keys())}", file=sys.stderr)
        sys.exit(1)

    # Aider special case: print launch command
    if agent == "aider":
        persona_file = Path(project_dir) / ".aider-persona.md"
        if not dry_run:
            persona_file.write_text(prompt_text)
        print("# Aider launch command:")
        print(f"aider --system-prompt \"$(cat {persona_file})\"")
        return

    # Write to target file
    target = Path(project_dir) / config["path"]
    content = config.get("comment", "") + "\n" + prompt_text + "\n"

    if dry_run:
        print(f"Would write to: {target}")
        print(f"\n{content[:500]}...")
        return

    target.write_text(content)
    print(f"✅ Written to {target} ({len(prompt_text)} chars)")
    print(f"   {config['description']}")


def save_to_store(seed: str, enhanced: str, agent: str, project: str, profile: str = None):
    """Auto-save this enhancement to the JSON store."""
    store_script = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompt-store.py")
    if not os.path.exists(store_script):
        return  # store not available
    subprocess.run(
        [PYTHON, store_script, "save",
         "--seed", seed[:500],
         "--enhanced", enhanced[:5000],
         "--agent", agent,
         "--project", project,
         "--profile", profile or "",
         "--quiet"],
        capture_output=True, timeout=10
    )


def main():
    parser = argparse.ArgumentParser(
        description="Install an enhanced system prompt into any AI coding agent's config"
    )
    parser.add_argument("seed", nargs="?", help="The rough prompt idea, or '-' for stdin")
    parser.add_argument("--file", "-f", help="Read seed from file")
    parser.add_argument("--agent", "-a", required=True,
                       choices=list(AGENT_CONFIGS.keys()) + ["all"],
                       help="Target agent (or 'all' for every compatible config)")
    parser.add_argument("--project", "-p", default=os.getcwd(),
                       help="Project directory (default: current dir)")
    parser.add_argument("--profile", choices=["senior-dev", "architect", "reviewer", "sre", "product", "mentor"],
                       help="Enhancement profile")
    parser.add_argument("--dry-run", action="store_true",
                       help="Show what would be written without writing")
    parser.add_argument("--json", action="store_true",
                       help="Output JSON for agent consumption")
    parser.add_argument("--no-store", action="store_true",
                       help="Skip saving to the analytics store")
    parser.add_argument("--keep", action="store_true",
                       help="Keep raw enhanced output (don't strip stderr prefix)")
    args = parser.parse_args()

    # Get seed
    if args.file:
        seed = args.file
        is_file = True
    elif args.seed == "-":
        seed = sys.stdin.read().strip()
        is_file = False
    elif args.seed:
        seed = args.seed
        is_file = False
    else:
        parser.error("Provide a seed prompt or --file")

    t0 = __import__('time').time()

    # Enhance
    if not args.json:
        print(f"Enhancing: {seed[:60]}...", file=sys.stderr)
    enhanced = enhance(seed, is_file)
    duration_ms = int((__import__('time').time() - t0) * 1000)

    # Strip "Enhancing with..." line from prompt-enhancer stderr
    if not args.keep:
        if "\n" in enhanced and enhanced.startswith("Enhancing"):
            enhanced = enhanced.split("\n", 1)[1] if "\n" in enhanced else enhanced

    # --json output mode (for AI agent consumption)
    if args.json:
        result = {
            "status": "ok",
            "seed": seed[:200],
            "enhanced": enhanced,
            "agent": args.agent,
            "project": args.project,
            "duration_ms": duration_ms,
        }
        print(json.dumps(result, ensure_ascii=False))
        # Still save to store
        if not args.no_store:
            save_to_store(seed, enhanced, args.agent, args.project, args.profile)
        return

    # Install to agent(s)
    agents = list(AGENT_CONFIGS.keys()) if args.agent == "all" else [args.agent]
    for agent in agents:
        if args.agent == "all" and agent == "aider":
            continue
        install(enhanced, agent, args.project, args.dry_run)

    # Save to analytics store
    if not args.no_store and not args.dry_run:
        save_to_store(seed, enhanced, args.agent, args.project, args.profile)


if __name__ == "__main__":
    main()
